services:
  composite_service:
    build: ./composite-service
    container_name: composite_microservice
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./composite-service/:/app/
    ports:
      - 8004:8000
    environment:
      # - DATABASE_URI=${DATABASE_URL}
      - BREEDER_SERVICE_URL=${LOCAL_BREEDER_SERVICE_URL}
      - PET_SERVICE_URL=${LOCAL_PET_SERVICE_URL}
      - CUSTOMER_SERVICE_URL=${LOCAL_CUSTOMER_SERVICE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PYTHONPATH=/app
      - URL_PREFIX=http://localhost:8084/api/v1
      # - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    # depends_on:
    #   - breeder_db

  # breeder_db:
  #   image: postgres:12.1-alpine
  #   container_name: breeder_db
  #   volumes:
  #     - postgres_data_breeder:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=breeder_db_username
  #     - POSTGRES_PASSWORD=breeder_db_password
  #     - POSTGRES_DB=breeder_db_dev

  nginx:
    image: nginx:latest
    container_name: composite_nginx
    ports:
      - "8084:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - composite_service
# volumes:
# postgres_data_movie:
# postgres_data_breeder:
